---
title: "Clustering Update"
author: "Constantin Zackl"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE}
suppressPackageStartupMessages({
  library(ggplot2)
  library(Seurat)
  library(dplyr)
  library(magrittr)
  library(BiocParallel)
  library(progressr)
  library(spatstat)
  library(sf)
  library(plotly)
  library(dplyr)
  library(tidyr)
  library(EBImage)
  library(colorspace)
library(dplyr)
library(ggplot2)
library(stats)
library(gridExtra)
})

```


```{r include=FALSE}
crop_parameters <- list(
  list(name="A3", x=c(11600, 12300), y=c(4350, 5050)),
  list(name="A4", x=c(11200, 12000), y=c(5250, 6000)),
  list(name="A7", x=c(10400, 11200), y=c(8450, 9250)),
  list(name="A11", x=c(9600, 10500), y=c(12550, 13200)),
  list(name="B3", x=c(10500, 11250), y=c(4000, 4750)),
  list(name="B4", x=c(10100, 10900), y=c(5050, 5800)),
  list(name="B11", x=c(8700, 9450), y=c(12400, 13000)),
  list(name="C1", x=c(10100, 10850), y=c(1700, 2500)),
  list(name="C2", x=c(9800, 10600), y=c(2700, 3500)),
  list(name="C3", x=c(9400, 10100), y=c(3800, 4500)),
  list(name="C4", x=c(9100, 9850), y=c(4700, 5400)),
  list(name="C6", x=c(8500, 9200), y=c(7100, 7800)),
  list(name="C9", x=c(7800, 8500), y=c(10000, 10750)),
  list(name="D1", x=c(9200, 10000), y=c(1100, 1800)),
  list(name="D2", x=c(8700, 9450), y=c(2400, 3200)),
  list(name="D3", x=c(8400, 9100), y=c(3350, 4050)),
  list(name="D4", x=c(8000, 8800), y=c(4700, 5400)),
  list(name="D6", x=c(7400, 8100), y=c(6700, 7400)),
  list(name="D7", x=c(7200, 8000), y=c(7700, 8400)),
  list(name="E1", x=c(8000, 8800), y=c(1000, 1800)),
  list(name="E2", x=c(7600, 8400), y=c(2200, 3000)),
  list(name="E3", x=c(7300, 8100), y=c(3200, 4000)),
  list(name="E4", x=c(7000, 7700), y=c(4300, 5050)),
  list(name="E6", x=c(6300, 7000), y=c(6700, 7300)),
  list(name="E11", x=c(5600, 6400), y=c(11700, 12400)),
  list(name="F1", x=c(6850, 7700), y=c(850, 1600)),
  list(name="F2", x=c(6550, 7250), y=c(1900, 2600)),
  list(name="F3", x=c(6300, 7050), y=c(2850, 3650)),
  list(name="F4", x=c(6000, 6700), y=c(4050, 4750)),
  list(name="F9", x=c(4600, 5400), y=c(9300, 10000)),
  list(name="G1", x=c(5700, 6500), y=c(550, 1350)),
  list(name="G2", x=c(5500, 6200), y=c(1550, 2400)),
  list(name="G3", x=c(5160, 5950), y=c(2800, 3550)),
  list(name="G4", x=c(4950, 5700), y=c(3800, 4550)),
  list(name="G5", x=c(4600, 5800), y=c(5100, 5800)),
  list(name="G7", x=c(4000, 4750), y=c(7100, 7800)),
  list(name="G10", x=c(3300, 4000), y=c(10200, 10900)),
  list(name="H1", x=c(4600, 5500), y=c(150, 1050)),
  list(name="H2", x=c(4350, 5100), y=c(1650, 2400)),
  list(name="H3", x=c(4100, 4900), y=c(2440, 3150)),
  list(name="H5", x=c(3500, 4200), y=c(4750, 5400)),
  list(name="H10", x=c(2250, 2950), y=c(10000, 10700)),
  list(name="I2", x=c(3300, 4100), y=c(1150, 1950)),
  list(name="J2", x=c(2200, 2950), y=c(900, 1650))
)
```

```{r include=FALSE}
data = readRDS("~/export/merfish2/merfishTMA3_annotated.rds")
```

### Remaining Cores after filtering: 

```{r echo=FALSE, collapse=TRUE}
cores <- unlist(lapply(crop_parameters, function(param) param$name))
cores
```

```{r echo=FALSE, fig.width=15}

all_cores_df <- data.frame(Core = character(), Cluster = factor(), Frequency = numeric())

for (core in cores) {
    cluster <- data$cell_type_level2[Cells(data[[core]])]
    cluster <- table(cluster)

    df <- data.frame(Core = rep(core, length(cluster)), Cluster = names(cluster), Frequency = as.numeric(cluster))

    all_cores_df <- rbind(all_cores_df, df)
}



frequency_matrix <- reshape2::dcast(all_cores_df, Core ~ Cluster, value.var = "Frequency", fill = 0)
row.names(frequency_matrix) <- frequency_matrix$Core
frequency_matrix <- frequency_matrix[, -1]

dist_matrix <- dist(frequency_matrix)
hc <- hclust(dist_matrix)

dendro <- as.dendrogram(hc)

ordered_cores <- factor(all_cores_df$Core, levels = row.names(frequency_matrix)[hc$order])

all_cores_df$Core <- ordered_cores  

all_cores_df$Cluster <- as.factor(all_cores_df$Cluster)

cluster_levels <- levels(all_cores_df$Cluster)

# level2
distinct_colors <- c(
  "B"                         = "#30A79C",
  "T/NK"                      = "#356884",
  "DC/Macro"                  = "#884AB9",
  "KC"                        = "#5F8F63",
  "Mel"                       = "#5A3E28",
  "prol. Mel"                 = "#463320",
  "low qual"                  = "#CCCCCC",
  "unclassified"              = "#E7E7E7",
  "VEC cluster1"              = "#b2182b",
  "VEC cluster2"              = "#ef3b2c",
  "LEC"                       = "#D86D70",
  "myFB & vSMC_atEC"          = "#E3B417",
  "myFB & vSMC_dist"          = "#FCCA46",
  "prol. FB & pericytes_atEC" = "#9D5C2F",
  "prol. FB & pericytes_dist" = "#B86E3C",
  "iCAF_atEC"                 = "#D96A1F",
  "iCAF_dist"                 = "#FE7F2D",
  "iCAF_aEtEC"                = "#D96A1F"  
)

  
# level1
# distinct_colors <- c(
#   "B"                    = "#30A79C",
#   "T/NK"                 = "#356884",
#   "DC/Macro"             = "#884AB9",
#   "KC"                   = "#5F8F63",
#   "Mel"                  = "#5A3E28",
#   "prol. Mel"            = "#463320",
#   "LEC"                  = "#D86D70",
#   "VEC cluster1"         = "#b2182b",
#   "VEC cluster2"         = "#ef3b2c",
#   "myFB & vSMC"          = "#FCCA46",
#   "prol. FB & pericytes" = "#B86E3C",
#   "iCAF"                 = "#FE7F2D",
#   "low qual"             = "#CCCCCC",
#   "unclassified"         = "#E7E7E7"
# )
# 
# # # level0
# distinct_colors <- c(
#   "B" = "#30A79C",
#   "T/NK" = "#356884",
#   "DC/Macro" = "#884AB9",
#   "KC" = "#5F8F63",
#   "Mel" = "#5A3E28",
#   "prol. Mel" = "#463320",
#   "LEC/VEC" = "#D86D70",
#   "FB" = "#FDA43A",
#   "low qual" = "#CCCCCC",
#   "unclassified" = "#E7E7E7"
# )

all_cores_df$Cluster <- factor(all_cores_df$Cluster, levels = rev(names(distinct_colors)))


tma = "TMA3"
level = "level2"


plot <- ggplot(all_cores_df, aes(x = Core, y = Frequency, fill = Cluster)) +
  geom_bar(stat = "identity", position = "fill") +
  scale_fill_manual(values = distinct_colors) +
  labs(
    title = paste("Cluster Composition", tma, level), 
    x = "Core", 
    y = "Frequency", 
    fill = "Cluster"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
    panel.background = element_rect(fill = "white", color = NA), 
    plot.background = element_rect(fill = "white", color = NA)  
  )


base_path = "~/export/merfish2/ClusterComp/"
filename <- file.path(base_path, paste0(tma, "_", level,  ".png"))

ggsave(filename = filename, plot = plot, width = 15, height = 10, dpi = 300)


plot <- plot(dendro, main=paste("Dendrogram of cluster composition", tma, level), xlab="Cores", ylab="Height")

```
