---
title: "Merscope Preprocessing"
author: "Constantin Zackl"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, collapse=TRUE}
suppressPackageStartupMessages({
  library(ggplot2)
  library(Seurat)
  library(dplyr)
  library(magrittr)
  library(BiocParallel)
  library(progressr)
  library(spatstat)  
  library(sf)
})
```

```{r}
options(future.globals.maxSize = 5 * 1024^3) # 5 GB

```


```{r loading data, collapse=TRUE}
start = Sys.time()
data <- LoadVizgen(data.dir = "~/merfish/TMA_1/", 
                   fov="full", 
                   assay = "Vizgen", 
                   verbose = T, 
                   metadata = c("volume", "fov"),
                   z=3L, 
                   use.BiocParallel=F, 
                   workers.MulticoreParam = 20)
end = Sys.time()

print(end-start)
```


```{r parameters, collapse=TRUE}
crop_parameters <- list(
  list(name="A2", x=c(7400, 8100), y=c(750, 1400)),
  list(name="A3", x=c(7450, 8100), y=c(1700, 2350)), 
  list(name="A4", x=c(7800, 8650), y=c(3500, 4250)),
  list(name="A5", x=c(7800, 8650), y=c(4500, 5400)),
  list(name="A6", x = c(7450, 8250), y = c(4850, 5550)), 
  list(name="A7", x = c(7450, 8250), y = c(5900, 6600)), 
  list(name="A8", x = c(7500, 8250), y = c(6950, 7600)),
  list(name="A9", x = c(7500, 8350), y = c(8000, 8700)),
  list(name="A10", x = c(7550, 8350), y = c(9100, 9800)),
  list(name="A11", x = c(7550, 8350), y = c(10100, 10800)),
  list(name="A15", x = c(7500, 8300), y = c(14200, 14850)),
  list(name="B2", x = c(6400, 7050), y = c(750, 1400)),
  list(name="B3", x = c(6400, 7050), y = c(1700, 2400)),
  list(name="B4", x = c(6400, 7100), y = c(2750, 3450)),
  list(name="B6", x = c(6450, 7150), y = c(4850, 5550)),
  list(name="B7", x = c(6450, 7200), y = c(5900, 6600)),
  list(name="B8", x = c(6450, 7200), y = c(6950, 7700)), 
  list(name="B9", x = c(6450, 7200), y = c(8000, 8800)),
  list(name="B10", x = c(6450, 7250), y = c(9050, 9750)),
  list(name="B11", x = c(6450, 7250), y = c(10100, 10800)),
  list(name="B15", x = c(6450, 7250), y = c(14200, 14850)),
  list(name="C2", x=c(7800, 8650), y=c(4500, 5400)), 
  list(name="C3", x = c(5300, 6150), y = c(1700, 2450)), 
  list(name="C4", x=c(5620, 6450), y=c(4500, 5550)), 
  list(name="C5", x = c(5350, 6200), y = c(3750, 4650)),
  list(name="C6", x = c(5350, 6200), y = c(4850, 5550)),
  list(name="C7", x = c(5450, 6200), y = c(5900, 6650)), 
  list(name="C8", x=c(1250, 2100), y=c(4500, 5550)),
  list(name="C9", x = c(5450, 6200), y = c(8000, 8800)),
  list(name="C15", x = c(5450, 6200), y = c(14200, 14900)), 
  list(name="D3", x = c(4350, 5100), y = c(1700, 2500)),
  list(name="D5",  x = c(4350, 5100), y = c(3850, 4650)),
  list(name="D6", x = c(4350, 5100), y = c(4900, 5550)),
   list(name="D7", x=c(3530, 4300), y=c(7100, 7900)), 
  list(name="D8", x = c(4350, 5100), y = c(7050, 7750)), 
  list(name="D9", x = c(4350, 5100), y = c(8000, 8800)),
  list(name="D10", x = c(4300, 5100), y = c(9050, 9850)),
  list(name="D11", x = c(4300, 5100), y = c(10100, 10820)),
  list(name="D15", x = c(4300, 5100), y = c(14200, 14950)),
  list(name="E4", x = c(3200, 3900), y = c(3000, 3550)),
  list(name="E5", x = c(3200, 3900), y = c(3850, 4650)), 
  list(name="E6", x = c(3200, 4000), y = c(4900, 5750)),
  list(name="E7", x = c(3200, 4000), y = c(6050, 6700)),
  list(name="E8", x = c(3200, 4000), y = c(7050, 7750)), 
  list(name="E9", x = c(3200, 4100), y = c(8050, 8800)),
  list(name="E10",  x = c(3200, 4100), y = c(9050, 9850)),
  list(name="E11", x = c(3250, 4100), y = c(10100, 10820)),
  list(name="E12", x=c(0, 1000), y=c(9750, 10500)),
  list(name="E13", x = c(3250, 4100), y = c(12150, 12850)), 
  list(name="E14", x = c(3350, 4100), y = c(13250, 13900)),
  list(name="E15", x = c(3350, 4100), y = c(14200, 15000)), 
  list(name="F4", x = c(2100, 2850), y = c(2950, 3700)),
  list(name="F5", x = c(2100, 2850), y = c(3950, 4650)), 
  list(name="F6", x = c(2100, 2850), y = c(4900, 5750)),
  list(name="F7", x = c(2100, 2850), y = c(6050, 6750)),
  list(name="F8", x = c(2100, 2850), y = c(7050, 7750)),
  list(name="F9", x = c(2100, 3000), y = c(8050, 8800)),
  list(name="F10", x = c(2100, 3000), y = c(9050, 9850)),
  list(name="F11", x = c(2100, 3000), y = c(10100, 10850)),
  list(name="F12", x=c(1500, 2100), y=c(11800, 12420)), 
  list(name="F13", x = c(2100, 3000), y = c(12150, 12900)),
  list(name="F14", x = c(2100, 3000), y = c(13250, 14000)), 
  list(name="F15",  x = c(2100, 3000), y = c(14200, 15000)),  
  list(name="G6",  x = c(1200, 1900), y = c(4900, 5750)),
  list(name="G7", x = c(1200, 1900), y = c(6050, 6800)), 
  list(name="G8", x = c(1200, 1950), y = c(7050, 7850)),
  list(name="G9", x = c(1150, 1950), y = c(8050, 8800)),
  list(name="G10", x = c(1150, 1950), y = c(9050, 9850)),
  list(name="G12",  x = c(1150, 1950), y = c(11150, 11950)),
  list(name="G13", x = c(1150, 2000), y = c(12150, 12950)), 
  list(name="G14", x = c(1150, 2000), y = c(13250, 14000)), 
  list(name="H3", x = c(0, 850), y = c(2150, 2700)),
  list(name="H7", x = c(0, 850), y = c(6050, 6850)),
  list(name="H8", x = c(0, 850), y = c(7050, 7850)),
  list(name="H11", x = c(0, 850), y = c(10100, 10850)),
  list(name="H12", x = c(0, 850), y = c(11150, 11950)),
  list(name="H14", x = c(0, 850), y = c(13250, 14050)))
```

```{r}
cores <- unlist(lapply(crop_parameters, function(param) param$name))
```




```{r cropping, collapse=TRUE}
# Set FOV
for (i in seq_along(crop_parameters)) {
    param <- crop_parameters[[i]]
    
    print(param$name)
    data[[param$name]] <- Crop(data[["full"]], x = param$x, y = param$y, coords = "plot") # set FOV
    DefaultBoundary(data[[param$name]]) <- "segmentation" # set boundary
}
```

```{r remove unwanted cells}
# remove cells not in cores
cells_in_cores <- c()
for (core in cores) {
  cells_in_cores <- append(cells_in_cores, Cells(data[[core]]))
}

# subset
suppressWarnings({
  data <- data[, cells_in_cores]
})
```

```{r preprocessing, collapse=TRUE}
data = SCTransform(data, assay = "Vizgen", clip.range = c(-10, 10))
data = RunPCA(data, npcs=25, features = rownames(data))
data = RunUMAP(data, dim=1:25)
data = FindNeighbors(data, dims = 1:25)
data = FindClusters(data, resolution = 0.5) 
```

```{r plots, fig.height=15, fig.width=15}
DimPlot(data, raster = F, label = T)
ImageDimPlot(data, fov = "full", group.by = "seurat_clusters", axes=T)
```

```{r save data}
saveRDS(data, file = "~/export/merfish2/merfishTMA1_all_except_wrong_tissue.rds")
```

